<?php

return [
    [
        'title' => 'Dashboard',
        'show' => true,
        'description' => 'Untuk melihat ringkasan aplikasi.',
        'icon' => 'home',
        'route-name' => 'dashboard.index',
        'is-active' => 'dashboard*',
        'category' => 'Aplication',
        'permission' => ['admin', 'user'],
    ],
    [
        'title' => 'Tes Ujian',
        'show' => true,
        'description' => 'Untuk memulai mengerjaikan Ujian tes.',
        'icon' => 'book-open-reader',
        'route-name' => 'tes-ujian.index',
        'is-active' => 'tes-ujian*',
        'category' => 'Aplication',
        'permission' => ['user'],
    ],
    [
        'title' => 'Identitas Sekolah',
        'show' => true,
        'description' => 'Melihat data identitas sekolah.',
        'icon' => 'school',
        'route-name' => 'indentitas-sekolah.index',
        'is-active' => 'indentitas-sekolah*',
        'category' => 'Aplication',
        'permission' => ['admin'],
    ],
    [
        'title' => 'Nilai PPDB',
        'show' => true,
        'description' => 'Melihat dan menilai hasil ujian ppdb.',
        'icon' => 'scroll',
        'route-name' => 'tes-ujian.nilai-tes',
        'is-active' => 'tes-ujian.nilai-tes*',
        'category' => 'Aplication',
        'permission' => ['admin'],
    ],
    [
        'title' => 'Slide Show',
        'show' => true,
        'description' => 'Menampilkan data slide show.',
        'icon' => 'sun',
        'route-name' => 'slide-show.index',
        'is-active' => 'slide-show.index',
        'category' => 'Landing Page',
        'permission' => ['admin'],
    ],
    [
        'title' => 'Profil',
        'show' => true,
        'description' => 'Menampilkan data profil anda.',
        'icon' => 'user',
        'route-name' => 'setting.user-profil.index',
        'is-active' => 'setting.user-profil.index',
        'category' => 'Account',
        'permission' => ['user'],
    ],
    [
        'title' => 'Setting',
        'show' => true,
        'description' => 'Menampilkan data akun.',
        'icon' => 'gear',
        'route-name' => 'setting.akun.index',
        'is-active' => 'setting*',
        'category' => 'Account',
        'permission' => ['admin'],
        'sub-menus' => [
            [
                'title' => 'Akun',
                'show' => true,
                'decription' => 'Menampilkan data akun.',
                'route-name' => 'setting.akun.index',
                'is-active' => 'setting.akun*',
                'permission' => ['admin'],
            ],
            [
                'title' => 'Profil',
                'show' => true,
                'decription' => 'Menampilkan data profil anda.',
                'route-name' => 'setting.user-profil.index',
                'is-active' => 'setting.user-profil.index',
                'permission' => ['admin'],
            ],
        ],
    ],
    [
        'title' => 'Berita',
        'show' => true,
        'description' => 'Menampilkan data berita.',
        'icon' => 'newspaper',
        'route-name' => 'menu-berita.index',
        'is-active' => 'menu-berita.*',
        'category' => 'Aplication',
        'permission' => ['admin'],
        'sub-menus' => [
            [
                'title' => 'Menu Berita',
                'show' => true,
                'decription' => 'Menampilkan data berita.',
                'route-name' => 'menu-berita.index',
                'is-active' => 'menu-berita*',
                'permission' => ['admin'],
            ],
            [
                'title' => 'Kategori Berita',
                'show' => true,
                'decription' => 'Menampilkan data kategori berita.',
                'route-name' => 'menu-berita.category',
                'is-active' => 'menu-berita.category',
                'permission' => ['admin'],
            ],
        ],
    ],
    [
        'title' => 'Kata Sambutan',
        'show' => true,
        'decription' => 'Halaman landing page',
        'icon' => 'user',
        'route-name' => 'kata-sambutan.index',
        'is-active' => 'kata-sambutan*',
        'category' => 'Landing Page',
        'permission' => ['admin'],
    ],
    [
        'title' => 'Menu Profil',
        'show' => true,
        'icon' => 'fa-light fa-address-card',
        'route-name' => null,
        'is-active' => 'menu-profil*',
        'permission' => ['admin'],
        'category' => 'Landing Page',
        'sub-menus' => [
            [
                'title' => 'Tujuan',
                'show' => true,
                'decription' => 'Tujuan',
                'route-name' => 'menu-profil.tujuan.index',
                'is-active' => 'menu-profil.tujuan*',
                'permission' => ['admin'],
            ],
            [
                'title' => 'Visi Misi',
                'show' => true,
                'decription' => 'Visi Misi',
                'route-name' => 'menu-profil.visi-misi.index',
                'is-active' => 'menu-profil.visi-misi*',
                'permission' => ['admin'],
            ],
            [
                'title' => 'Makna Logo',
                'show' => true,
                'decription' => 'Makna Logo',
                'route-name' => 'menu-profil.makna-logo.index',
                'is-active' => 'menu-profil.makna-logo*',
                'permission' => ['admin'],
            ],
            [
                'title' => 'Sejarah',
                'show' => true,
                'decription' => 'Sejarah',
                'route-name' => 'menu-profil.sejarah.index',
                'is-active' => 'menu-profil.sejarah*',
                'permission' => ['admin'],
            ],
            [
                'title' => 'Struktur Organisasi',
                'show' => true,
                'decription' => 'Struktur Organisasi',
                'route-name' => 'menu-profil.struktur-organisasi.index',
                'is-active' => 'menu-profil.struktur-organisasi*',
                'permission' => ['admin'],
            ],
        ],
    ],
    [
        'title' => 'Master',
        'show' => true,
        'icon' => 'database',
        'route-name' => null,
        'is-active' => 'master*',
        'permission' => ['admin'],
        'category' => 'Manage',
        'sub-menus' => [
            [
                'title' => 'Siswa',
                'show' => true,
                'description' => 'Melihat data siswa.',
                'route-name' => 'master.siswa.index',
                'is-active' => 'master.siswa*',
                'permission' => ['admin'],
            ],
            [
                'title' => 'Ujian',
                'show' => true,
                'description' => 'Melihat data yg berhubungan ujian tes.',
                'route-name' => 'master.ujian.index',
                'is-active' => 'master.ujian*',
                'permission' => ['admin'],
            ],
        ],
    ],
    [
        'title' => 'PPDB',
        'show' => true,
        'icon' => 'user-graduate',
        'route-name' => null,
        'is-active' => 'verifikasi*',
        'permission' => ['admin'],
        'category' => 'Manage',
        'sub-menus' => [
            [
                'title' => 'Verifikasi Siswa',
                'show' => true,
                'description' => 'Melihat data verifikasi siswa.',
                'route-name' => 'verifikasi.siswa',
                'is-active' => 'verifikasi.siswa',
                'permission' => ['admin'],
            ],
            [
                'title' => 'Verifikasi Kelulusan',
                'show' => true,
                'description' => 'Melihat data verifikasi kelulusan.',
                'route-name' => 'verifikasi.kelulusan',
                'is-active' => 'verifikasi.kelulusan',
                'permission' => ['admin'],
            ],
        ],
    ],
];
